#!/usr/bin/env bash
# Configure the Sentinel layer post-deployment.
#
# Prerequisites:
#   - Deploy + smoke-test already complete (.env has SENTINEL_* addresses)
#   - DEPLOYER_PRIVATE_KEY funded with ~0.6 STT (registrations + Coordinator
#     native funding + config tx gas)
#   - SCORER_AGENT_ID and ROUTER_AGENT_ID set in .env to the on-chain Somnia
#     native agent IDs (e.g. the llm-inference base agent's numeric ID).
#     Look these up via the Agent Explorer at
#     https://agents.testnet.somnia.network or by querying the platform
#     contract directly.
#
# What this does:
#   1. Registers four Sentinel agents owned by the deployer in AgentRegistry:
#      Watcher, Scorer, Router, Executor. Returns their on-chain IDs.
#   2. Wires the Coordinator's Sentinel agent slots to those IDs via
#      setScorerSentinelAgentId / setRouterSentinelAgentId.
#   3. Wires the Coordinator's Somnia native agent slots to the IDs in
#      SCORER_AGENT_ID / ROUTER_AGENT_ID via setScorerSomniaAgentId and
#      setRouterSomniaAgentId.
#   4. Funds the Coordinator with 0.5 STT so it can pay createRequest
#      deposits for the next few cases.
#   5. Appends WATCHER_AGENT_ID and EXECUTOR_AGENT_ID to .env so the
#      Watcher and Executor binaries can pick them up.

set -euo pipefail

if [ ! -f .env ]; then
  echo "FATAL: .env not found" >&2
  exit 1
fi
set -a
# shellcheck disable=SC1091
. ./.env
set +a

req_env() {
  if [ -z "${!1:-}" ]; then
    echo "FATAL: $1 not set in .env" >&2
    exit 1
  fi
}
for v in \
  SOMNIA_RPC_HTTP DEPLOYER_PRIVATE_KEY \
  SENTINEL_AGENT_REGISTRY SENTINEL_COORDINATOR \
  SCORER_AGENT_ID ROUTER_AGENT_ID; do
  req_env "$v"
done

RPC="$SOMNIA_RPC_HTTP"
DEPLOYER=$(cast wallet address "$DEPLOYER_PRIVATE_KEY")

GAS_LIMIT=16000000
send_tx() {
  cast send \
    --private-key "$DEPLOYER_PRIVATE_KEY" \
    --rpc-url "$RPC" \
    --gas-limit "$GAS_LIMIT" \
    --json \
    "$@"
}

# The Role enum on AgentRegistry: None=0, Watcher=1, Scorer=2, Router=3, Executor=4.
register_agent() {
  local role="$1" name="$2"
  local lower_name
  lower_name=$(echo "$name" | tr '[:upper:]' '[:lower:]')
  echo "  Registering $name (role=$role)..." >&2
  # Read nextAgentId BEFORE the registration so we know the ID that will be
  # assigned. This avoids depending on receipt-log parsing.
  local agent_id
  agent_id=$(cast call "$SENTINEL_AGENT_REGISTRY" "nextAgentId()(uint256)" --rpc-url "$RPC" | sed 's/ \[.*\]//')
  echo "  -> $name will be registered as agent ID: $agent_id" >&2
  cast send \
    --private-key "$DEPLOYER_PRIVATE_KEY" \
    --rpc-url "$RPC" \
    --gas-limit "$GAS_LIMIT" \
    "$SENTINEL_AGENT_REGISTRY" \
    "register(uint8,string)" "$role" "ipfs://sentinel/${lower_name}/v1" \
    2>&1 | grep -E "(status|gasUsed)" >&2
  printf '%s' "$agent_id"
}

hr() { printf '\n========== %s ==========\n' "$1"; }

# ---- Phase 1: Register agents ----------------------------------------------
hr "Phase 1: register Sentinel agents owned by deployer"
WATCHER_ID=$(register_agent 1 "Watcher")
SCORER_ID=$(register_agent 2 "Scorer")
ROUTER_ID=$(register_agent 3 "Router")
EXECUTOR_ID=$(register_agent 4 "Executor")

# ---- Phase 2: Configure Coordinator ----------------------------------------
hr "Phase 2: set Coordinator's Sentinel agent IDs"
echo "  setScorerSentinelAgentId($SCORER_ID)"
send_tx "$SENTINEL_COORDINATOR" "setScorerSentinelAgentId(uint256)" "$SCORER_ID" > /dev/null
echo "  setRouterSentinelAgentId($ROUTER_ID)"
send_tx "$SENTINEL_COORDINATOR" "setRouterSentinelAgentId(uint256)" "$ROUTER_ID" > /dev/null

hr "Phase 3: set Coordinator's Somnia native agent IDs"
echo "  setScorerSomniaAgentId($SCORER_AGENT_ID)"
send_tx "$SENTINEL_COORDINATOR" "setScorerSomniaAgentId(uint256)" "$SCORER_AGENT_ID" > /dev/null
echo "  setRouterSomniaAgentId($ROUTER_AGENT_ID)"
send_tx "$SENTINEL_COORDINATOR" "setRouterSomniaAgentId(uint256)" "$ROUTER_AGENT_ID" > /dev/null

# ---- Phase 4: Fund Coordinator ---------------------------------------------
hr "Phase 4: fund Coordinator with 0.5 STT for createRequest deposits"
cast send \
  --private-key "$DEPLOYER_PRIVATE_KEY" \
  --rpc-url "$RPC" \
  --value 0.5ether \
  "$SENTINEL_COORDINATOR" | grep -E "(transactionHash|status)" || true
echo "  Coordinator STT balance: $(cast balance "$SENTINEL_COORDINATOR" --rpc-url "$RPC" --ether)"

# ---- Phase 5: Persist agent IDs to .env -------------------------------------
hr "Phase 5: append agent IDs to .env so the runtimes can pick them up"
# Remove any existing lines first to avoid duplicates.
sed -i.bak -E '/^(WATCHER_AGENT_ID|EXECUTOR_AGENT_ID|SCORER_SENTINEL_AGENT_ID|ROUTER_SENTINEL_AGENT_ID)=/d' .env
rm -f .env.bak
{
  echo ""
  echo "# --- Sentinel layer agent IDs (auto-generated by configure-sentinel.sh) ---"
  echo "WATCHER_AGENT_ID=$WATCHER_ID"
  echo "EXECUTOR_AGENT_ID=$EXECUTOR_ID"
  echo "SCORER_SENTINEL_AGENT_ID=$SCORER_ID"
  echo "ROUTER_SENTINEL_AGENT_ID=$ROUTER_ID"
} >> .env

cat <<EOF

============================================================
DONE. Sentinel layer is fully configured.

Watcher agent ID:  $WATCHER_ID
Scorer agent ID:   $SCORER_ID
Router agent ID:   $ROUTER_ID
Executor agent ID: $EXECUTOR_ID

Coordinator funded with 0.5 STT for Somnia createRequest deposits.

Next:
  1. (If you have not already) run scripts/smoke-test.sh to set up a
     liquidatable position on the LendingPool.
  2. Start the Watcher: npm run watcher -w @sentinel/agents
  3. Start the Executor: npm run executor -w @sentinel/agents
  4. Observe the on-chain case state machine in shannon-explorer.

============================================================
EOF
